spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/Avanzada
# configuracion de springboot para conectarse a la base de datos local que se creara usando MySQL
# Astolfo3S@  --PASSWORD MYSQL FEDORA
#Aviso Es MongoDB spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/MyBaseAvanzada
#    username: root
#    password: Astolfo3S@
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:


#    database-platform: org.hibernate.dialect.MySQLDialect
#    hibernate:
#      ddl-auto: update