### LOGIN - Obtener token JWT y guardarlo como variable
POST http://localhost:8080/v1/auth/login
Content-Type: application/json

{
  "email": "jsebasdroid31@gmail.com",
  "password": "12345aBc"
}

> {%
    // Extraer y guardar el token en la variable global 'jwtToken'
    const json = await response.json();
    client.global.set("jwtToken", json.token);
%}

###

### CREAR REPORTE usando el token guardado
POST http://localhost:8080/v1/reports
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "title": "incendio en biblioteca",
  "contenido": "se esta quemando la biblioteca escolar",
  "image": "https://sources.com/img1.jpg",
  "location": {
    "latitud": 4.7110,
    "longitud": -74.0721
  },
  "categories": [
    {
      "description": "fuego",
      "name": "imprevisto"
    }
  ],
  "fechaSuceso": "2025-05-11"
}

###

### ACTUALIZAR REPORTE (PUT) usando el mismo token
PUT http://localhost:8080/v1/reports/095df97b-b2d7-42cc-ae6a-60bc1ce30323
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "title": "incendio en biblioteca",
  "contenido": "se esta quemando la biblioteca UNIVERSITARIA JAPONESA",
  "image": "https://sources.com/img1.jpg",
  "location": {
    "latitud": 4.7110,
    "longitud": -74.0721
  },
  "categories": [
    {
      "description": "fuego",
      "name": "imprevisto"
    }
  ],
  "fechaSuceso": "2025-05-11"
}

###

### ELIMINAR REPORTE (DELETE) usando el mismo token
DELETE http://localhost:8080/v1/reports/095df97b-b2d7-42cc-ae6a-60bc1ce30323
Content-Type: application/json
Authorization: Bearer {{jwtToken}}
