### Prueba de activacion de cuenta con FULL JWT
POST http://localhost:8080/v1/users
Content-Type: application/json

{
  "email": "jsebasdroid31@gmail.com",
  "password": "12345aBc",
  "fullname": "Usuario de Prueba",
  "dateBirth": "1990-05-12",
  "direccion": "av 30 de nov #10-72",
  "imagenPerfil": "http://sources/img1.jpg",
  "rol": "USERDEFAULT",
  "telefono": "+123456789012",
  "ubicacionUsuario": {
    "latitud": 4.79900,
    "longitud": -49.5600
  }
}

### Una vez recibido el codigo al correo, activar la cuenta
POST http://localhost:8080/v1/auth/activate
Content-Type: application/json

{
  "email": "jsebasdroid31@gmail.com",
  "activationCode": "10e051b8-a3b0-4e3a-a0f9-5cf9b146e95f"
}


### Una vez recibido el codigo al correo y haber activado la cuenta, LOguearse
POST http://localhost:8080/v1/auth/login
Content-Type: application/json

{
"email": "jsebasdroid31@gmail.com",
"password": "12345aBc"
}

