###
POST http://localhost:8080/v1/users
Content-Type: application/json

{
  "email": "usuario@mail.com",
  "password": "12345aBc",
  "fullname": "Usuario de Prueba",
  "dateBirth": "1990-05-12",
  "direccion": "av 30 de nov #10-72",
  "imagenPerfil": "http://sources/img1.jpg",
  "rol": "USERDEFAULT",
  "telefono": "+123456789012",
  "ubicacionUsuario": {
    "latitud": 4.79900,
    "longitud": -49.5600
  }
}

### probar un reporte
POST http://localhost:8080/v1/reports
Content-Type: application/json

{
  "title": "incendio en biblioteca",
  "content": "se esta quemando la biblioteca escolar",
  "occurrenceDate": "2025-05-15",
  "imageUrl": "http://sources/img1.jpg",
  "categories": ["SEGURIDAD"],
  "createdAt": "2025-05-15"
}
