###
POST http://localhost:8080/v1/users
Content-Type: application/json

{
  "email": "usuario@mail.com",
  "password": "12345aBc",
  "fullname": "Usuario de Prueba",
  "dateBirth": "1990-05-12",
  "direccion": "av 30 de nov #10-72",
  "imagenPerfil": "http://sources/img1.jpg",
  "rol": "USERDEFAULT",
  "telefono": "+123456789012",
  "ubicacionUsuario": {
    "latitud": 4.79900,
    "longitud": -49.5600
  }
}

### probar un reporte
POST http://localhost:8080/v1/reports
Content-Type: application/json

{
  "title": "incendio en biblioteca",
  "contenido": "se esta quemando la biblioteca escolar",
  "occurrenceDate": "2025-05-15",
  "image": "http://sources/img1.jpg",
  "location": {
    "latitud": 4.7110,
    "longitud": -74.0721
  },
  "categories": [
    {
      "id": "2332333",
      "description": "fuego"
    }
  ],
  "fechaSuceso": "2025-02-15",
  "listaComentarios": [
    {
      "creadorId": {
      },
      "contenido_comentario": "yo llame los bomberos",
      "fechaCreacion": "2025-02-15"
    }
  ],
  "importanceCount": 0,
  "userId_creador": "",
  "status": "PENDIENTE"
}


### probar un reporte
POST http://localhost:8080/v1/reports
Content-Type: application/json

{
  "title": "Incendio en biblioteca",
  "contenido": "Se está quemando la biblioteca escolar",
  "fechaSuceso": "2025-02-15",
  "image": "http://sources/img1.jpg",
  "location": {
    "latitud": 4.7110,
    "longitud": -74.0721
  },
  "categories": [
    {
      "id": 1,
      "nombre": "Incendio"
    }
  ],
  "listaComentarios": [
    {
      "autor": "Juan Pérez",
      "contenido": "Este incidente es muy preocupante."
    }
  ],
  "importanceCount": 0,
  "userId_creador": "usuario123",
  "status": "PENDIENTE"
}